### ISSUE TITLE
New dynamic SIGN

### ISSUE THREAD

**Issue by TELLO0815** [whatwedo/SyliusDatatransPaymentPlugin#1]
Hi there,

was in contact with Ueli ;-)
Here is the code to make it still work to summer 2024 with dynamic sign. For sign use the HMAC key:

```
////

$secret = $this->sign;
        $make_sign = $this->merchantId.$payment->getAmount().$payment->getCurrencyCode().$payment->getOrder()->getNumber();
        $dyn_sign = hash_hmac('sha256', $make_sign, hex2bin($secret));

////

'sign' => $dyn_sign,

////
```

**Comment by tuxes3** [comment]
Hello. I just released [`v1.0.0`](https://packagist.org/packages/whatwedo/sylius-datatrans-payment-plugin#v1.0.0). 

To activate it: 
 - update this package to the newest version
 - enable `Hmac sha256` in the admin (payment-methods) backend
 - enter your `HMAC` in the `sign` field (if the `Hmac sha256`-Option is disabled this field is used for the static sign)
